//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutdoorOrders.WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int OrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> SalespersonID { get; set; }
        public Nullable<int> CustomerBranchID { get; set; }
        public Nullable<decimal> TotalPrices { get; set; }
        public Nullable<decimal> TotalQuantaty { get; set; }
        public Nullable<decimal> TotalValues { get; set; }
        public Nullable<decimal> TotalDiscounts { get; set; }
        public Nullable<decimal> TotalTaxes { get; set; }
        public Nullable<decimal> OrderDiscount { get; set; }
        public Nullable<decimal> OrderTax { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<bool> IsHold { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsRefused { get; set; }
    
        public virtual CustomersBranches CustomersBranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual Salespersons Salespersons { get; set; }
    }
}
