//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutdoorOrders.WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salespersons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salespersons()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int SalespersonID { get; set; }
        public string SalespersonName { get; set; }
        public string SalespersonPhone { get; set; }
        public string SalespersonAddress { get; set; }
        public string SalespersonEmail { get; set; }
        public string SalespersonPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
